describe('Test crear post solo titulo', () => {
  beforeEach(() => {
    cy.visit('http://localhost:2368/ghost/')
    cy.wait(7000)
    cy.get('input.gh-input.email').type('pruebatester494@gmail.com')
    cy.get('input.gh-input.password').type('Abcd.123**')
    cy.get('button.login.gh-btn.gh-btn-login.gh-btn-block.gh-btn-icon.ember-view').click()
    cy.wait(2000)
    cy.url().should('eq', 'http://localhost:2368/ghost/#/dashboard')
    cy.visit('http://localhost:2368/ghost/#/posts')
  })
  it('Crear un nuevo post', ()=>{
    cy.get('a[href="#/editor/post/"]').eq(0).click()
    cy.wait(5000)
    cy.get('.gh-editor-title.ember-text-area.gh-input.ember-view').type('Primera Prueba Automatizada')
    cy.wait(3000)
    cy.get('.kg-prose').click()
    cy.wait(3000)
    cy.get('button.gh-btn.gh-btn-editor.darkgrey.gh-publish-trigger').eq(0).click()
    cy.wait(3000)
    cy.get('button.gh-btn.gh-btn-black.gh-btn-large').click()
    cy.wait(3000)
    cy.get('button.gh-btn.gh-btn-large.gh-btn-pulse.ember-view').click()
    cy.wait(5000)
    cy.get('a[href="#/dashboard/"]').eq(0).click({ force: true })
    cy.wait(2000)
    cy.url().should('eq', 'http://localhost:2368/ghost/#/dashboard')
    cy.visit('http://localhost:2368/ghost/#/posts')
    cy.wait(2000)
    cy.url().should('eq', 'http://localhost:2368/ghost/#/posts')
  })
})